### ISSUE TITLE
Надо будет придумать как сделать блок секций красиво

### ISSUE THREAD

**Issue by rudnitskih** [JukaChu/Uber-Eats-React#17]
![image](https://user-images.githubusercontent.com/8848858/60752692-76b40000-9fd1-11e9-8e86-71beae547696.png)

**Comment by scandy5** [comment]
![image](https://user-images.githubusercontent.com/41551315/61187917-71fde480-a680-11e9-87a9-a514213f9078.png)
Не сходство с макетом
