### ISSUE TITLE
Не понял прикола

### ISSUE THREAD

**Issue by rudnitskih** [JukaChu/Uber-Eats-React#20]
![image](https://user-images.githubusercontent.com/8848858/60752708-c8f52100-9fd1-11e9-9768-31cbd55f22d1.png)

https://github.com/JukaChu/Uber-Eats-React/blob/ab9b5da3acd76a852af0e7f2145872fdd5398c67/src/components/Cabinet/Cabinet.css

**Comment by scandy5** [comment]
done, can be closed
